### ISSUE TITLE
Links to other Groups/Bodies?

### ISSUE THREAD

**Issue by PaulJRobinson** [openpolitics/manifesto#169]
We link to books as reference material or background reading on the front page. Is it worth linking to groups for whom we are broadly supportive? They can be useful for inspiration. They are also good 'indicators' to first time visitors as to our overall direction. For example I would propose http://www.electoral-reform.org.uk/ and http://www.secularism.org.uk/ and http://www.neweconomics.org/as being three worthy groups whose campaigns are broadly in sync with our own stated policies. I'm sure there are plenty of others.

What does everyone think?

**Comment by Floppy** [comment]
Moved to https://github.com/openpolitics/openpolitics.github.io/issues/2

**Comment by Floppy** [comment]
This issue was moved to SomethingNewUK/somethingnewuk.github.io#18
