### ISSUE TITLE
'Open Parliament' as a side project of Open Manifesto

### ISSUE THREAD

**Issue by PaulJRobinson** [openpolitics/manifesto#185]
So we have here our Open Manifesto. I'm intrigued by what others have done in the YourVoice Party who are on the South East ballot for the European Parliamentary election tomorrow and have pledged that their MEPs will operate on a Direct Democracy basis for all legislation in the European Parliament - throwing it open to their constituents and casting their votes to match. I wondered whether there is any merit in having an Open Parliament on this site: All legislation (EU or Westminster) that is being debated could be automatically presented as a choice on the site, and everyone gets to vote on that legislation in favour or against it. If we can't get Direct Democracy for real, let's pretend we have it and just let everyone vote on each Bill anyway. Thoughts?

**Comment by Floppy** [comment]
Going to close this discussion here, as it's not for this project specifically, but we should remember it. I think there might be projects doing exactly this, I'll have a look around.
