### ISSUE TITLE
Move Parliament out of London

### ISSUE THREAD

**Issue by Floppy** [openpolitics/manifesto#253]
Need to write a proposal to move Parliament somewhere more northerly.<br><br>
via Email<br>
December 12, 2014 at 08:51PM

**Comment by frabcus** [comment]
:+1:

**Comment by Floppy** [comment]
Thanks for the +1 :)

I actually need to write up a proposal on this. Meaning to look at what twitter.com/ParliamentNorth are proposing, see if we can adopt it.

**Comment by Floppy** [comment]
I did it! See #266.
