### ISSUE TITLE
Use of proprietary software / services in the public sector

### ISSUE THREAD

**Issue by TheRyanHowell** [openpolitics/manifesto#290]
Just wondering what people's opinions were on the use of proprietary software / services in the public sector. Is there any data we can use to see how much we are spending on such software / services?

[There was news from last year about the UK government spending £5.5 billion on expanding the support for Windows XP.](http://www.theguardian.com/technology/2014/apr/07/uk-government-microsoft-windows-xp-public-sector)

I dare not dream just how much money we waste so people can use Microsoft Windows / Office in the public sector. There are open source alternatives that would make us more cost efficient and progressive as a society.

Anyone have some thoughts they would like to share on this? I was going to create a pull request, but not sure where this would go / what specifics people would want to put in the manifesto.

**Comment by Floppy** [comment]
Yes, definitely would be up for something on this. Perhaps it would fit in the economy section for now? I know GDS have done some stuff on standardising on open formats, so it's an evolution of that I guess.
