### ISSUE TITLE
Contributor stats

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/manifesto#314]
Might not be a good thing :) but...

Could we do stats? For example, for each contributor show the percentage of PRs successfully merged? 

It'd be nice to show whose good at writing good proposals, and that can be used as a pointer to new folks looking at how to go about adding their ideas.

**Comment by Floppy** [comment]
We could include something like that in the votebot, which I'm partway through a rewrite of... nice idea.

**Comment by Floppy** [comment]
This issue was moved to openpolitics/votebot#90
