### ISSUE TITLE
What is our focus?

### ISSUE THREAD

**Issue by yellowgopher** [openpolitics/manifesto#332]
I have a big issue that I feel needs to be addressed immediately.

A free, fair and tolerant society needs to be just that, free, fair AND tolerant.  When I looked at getting involved in this project I was under the impression that these values would be upheld but I fear we are moving to a position where we are losing the tolerance and, in reality, only a particular group get true freedom to air their views; rapidly jumping on and closing down any one who chooses to put forward an alternative viewpoint. 

This is fine, if that is the aim, but we are not really producing a manifesto that reflects the overall views of the population, as a whole, if a representative example do not get a fair say - which I would argue they are not.  (I admit this was always going to be a risk!)

There is a lot of good stuff being discussed but there is a risk that that this is undermined if a narrow focus group get too much say.

The tolerance, fairness and freedom disappear when that happens.

So, what's the plan?  Is this going to be a narrow focused, secular, anti-establishment party or something that reflects the values I would want to see - freedom, fairness and tolerance?

At the moment it is rapidly becoming the former.

**Comment by Floppy** [comment]
Can you point to specific instances of intolerance, or where we're not focused on freedom and fairness? We certainly want to be all those things you mention, but I admit that I might be as blind to my own intolerance as anyone else can be. 

If this is based off the recent spate of pull requests around secularism, that is simply reflective of someone becoming involved afresh and bringing a bunch of new ideas (which may or may not be integrated).

I agree that this stuff is hard, and we need to hold ourselves to account and try to remain fair. But, it's never been the intention to please everyone. We aren't building something that represents everyone equally; that takes a much more complex direct democratic system, I think. This project is building a manifesto for a particular (emergent, not pre-selected) view of the world, but in an open way where all ideas can get an airing, at least.

Again, if there are particular instances that you think are shutting down debate, or being intolerant towards new ideas, please link them here.

**Comment by Floppy** [comment]
In terms of who is involved, I agree we need more diversity, and more viewpoints. But, we are constrained by those who are actively participating. We can't force people to get involved, we can only encourage people to by spreading the message wherever we can.

**Comment by yellowgopher** [comment]
The secular argument is one area that is spreading throughout the manifesto - it is the big one at the moment - and I would point out that it has been there from the beginning (it isn't new).  Whereas I think the right approach would be to develop policies that would allow people to decide how to develop secular or religious activities in this country, to even things up, the manifesto is swinging completely the other way - almost to a point of penalising those with religious views (taking the latest studies (which were not  particularly extensive) around a third of the population!).  Even if I weren't a "religious nut" as I am sure I would be labelled (although that is not a true description of my views) I would say that is totally intolerant and much removed from what I (perhaps mistakenly) thought the point of the exercise was...
It's not about pleasing everyone - not everyone can be pleased - but the people with power (i.e. those of you who have the say in approving or not approving items) need to be aware that there are themes developing here that  are not necessarily reflective of society as a whole. 
As I said, originally, this was always going to be a risk.  If 10 people are participating and 9 of them hold a particular view, it matters not what the 64,999,990 other people in the country think!  I get that.  
But, as I said, you guys hold the power - so you have to decide whether you focus entirely on what you believe or try to form some sort of policy on how you determine whether something has real value or not... 
I.e. step back from your views a bit more :-)

**Comment by Floppy** [comment]
Secularism isn't about punishing religion, in any way, and if we're doing that, we're doing it wrong. It's about the state not favouring any one religion. People have complete freedom to follow whichever religion they like, to teach their children any religion they like, and so on. But, and this *is* currently a core belief of the manifesto, the state should have no part in it. That's what freedom of religion *is*, truly.

I have no wish for any religion to feel persecuted, but I would like all religions to be treated equally and not for one to have a higher status than the rest. That's how I define tolerance and freedom, personally. Obviously, if you are a follower of a religion that is currently closely linked to the state and threatened with disestablishment, then I guess it can seem the other way round.

Even among the third of the population that is religious, there is a wide range of belief, so encoding one religion into the state seems wrong in our present society.

**Comment by Floppy** [comment]
But, I accept that that comment above comes from my secular point of view.

**Comment by yellowgopher** [comment]
And that is fine... but the policies being developed are predominantly anti (I don't like the term "religion" to be fair, everyone has a "religion" or "belief" in something).  I think the approach is wrong - it needs to be focused on policy to allow choice - and if that choice is secular, fine, if it's the big red pepper in the bottom of my garden then fine too!  But that is never going to be aired enough at this time because the people involved are too tied up in their opinion to consider this...!
But, let's move on from religion.  It's is, after all, just representative of the greater issue - we are not giving people the choice here - we are developing into just another form of what has been on offer before.
We need to focus on true democracy - give people the choice. Advise the facts, yes, the options, yes, but facilitate policies that allow local people to make up their own mind; in a workable system.  Simple huh?
That goes for secularism, for monarchy, for democracy, for education, for freedom of speech and information, for defence, for everything.  Why are we falling into the trap that all the other parties do, fostering our opinions on the masses, when we could be so different and give them choice; ask them to make up their minds?
Human nature perhaps.

**Comment by Floppy** [comment]
One final word on religion - I personally do not have anything I class as a religion or belief in something, so it's definitely not *everyone*.

Anyway.

The idea is that yes, we can move forward to direct democracy where everyone has a choice on everything, but that will take time, and a number of other things along the way. We can't jump straight to it, so this is an experiment in allowing people to have their say in a way more similar to the current system *first*, while we attempt to move towards direct democracy over time, which will be a different system from this. Does that make any sense? Is it that, perhaps, that we need to clarify?

**Comment by yellowgopher** [comment]
I think you believe in this cause!!

My point remains, we need to be careful not to emphasise particular areas too much... and that is down to the moderators I am afraid!

**Comment by yellowgopher** [comment]
Slept on this and I think a clarification is needed.  Let me think of some wording and put it forward - I think this is all wrapped up in my confusion/concern... no confusion is the right word... about our stance on the constitution.  I think we might be getting too hung up on detailed stuff when what we need is an overall direction and individual policies that help us to get to the goal.  Localism/direct democracy is the pearl in the oyster here - that's the ticket that could sell (it sets us apart)...

OK?
