### ISSUE TITLE
The City of London

### ISSUE THREAD

**Issue by andrewdwilliams** [openpolitics/manifesto#347]
Make no mistake - the City of London Corporation is the [enemy of progress](http://www.newstatesman.com/economy/2011/02/london-corporation-city). Allowing the City of London to continue fundamentally conflicts with the fact we want government to be open, transparent and accountable, and also if we want it to be bottom-up rather than top-down. The question is what exactly to do with it. I've got a few ideas:

Repeal Clause 13 of the Magna Carta, which reinforces the City's privileges.
Include the assets of the City of London Corporation in the Freedom of Information Act
Abolish the business vote in Corporation elections
or simply Abolish the City of London Corporation (could be a long-term policy)

This goes hand in hand with an already established policy about abolishing the ministerial position of City Minister, and the policy that's in the voting queue on abolishing the role of City Remembrancer, or at least removing it from the floor of the House of Commons and removing it's privileges in viewing some legislation in the drafting stage.

**Comment by philipjohn** [comment]
Please, please, please turn this into a proposal! :)

**Comment by andrewdwilliams** [comment]
Not sure which category to put it under because the policies all come from different areas of concern. How about society?

**Comment by philipjohn** [comment]
I'd say democracy. We could split it out later if we feel it necessary.

**Comment by andrewdwilliams** [comment]
Done - #360.
