### ISSUE TITLE
Rules for granting merge rights

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/manifesto#353]
At present, only two of us have the privileges to merge proposals into the manifesto. Granting new users access is an entirely manual and subjective process.

We should figure out (if we want to) some rules around who gets this access and when. It should probably be some sort of merit-based rule.

Some ideas;

* Number/proportion of adopted proposals
* % of proposals contributed to (voted/discussed)

Of course, we may decide this is irrelevant because we can be auto-merging with votebot.

**Comment by Floppy** [comment]
I'd rather make this automatic with the votebot, though there will always be a need for human intervention on conflicts. The new editor means that we can add more admins though, certainly, and they don't need to be github-savvy.

Agreed there should be a rule though. At the moment repo admin is using a benign-dictatorship model :)

**Comment by philipjohn** [comment]
:+1:

**Comment by Floppy** [comment]
I'll move this to an issue on the votebot repo.
