### ISSUE TITLE
Airport Expansion Discussion

### ISSUE THREAD

**Issue by andrewdwilliams** [openpolitics/manifesto#358]
I'm opening this so we can have a discussion on airport expansion without having to take a vote. I've done this because the London Mayor draft manifesto, and one of the main issues in Lindsey's Garrett's campaign, is to expand Heathrow airport. 

This is what the draft manifesto says: 
> As long as there are strict limits on noise and pollution emissions, the expansion of Heathrow is set to bring 70,000 jobs to London; jobs that Londoners need and a transport asset that our city needs if it is going to remain internationally competitive. 

> Boris Johnson is a well-paid politician, now an MP and in the Cabinet as well as being a well-paid writer. The luxury he has to come up with fantasy plans for £50 billion island airports is not the luxury the average Londoner has when they simply need a job. 

> Heathrow expansion is a difficult decision but if the experts say that’s the cheapest and quickest way to bring jobs to London and if the environmental impact can be limited, then I’m prepared to go to those people who are affected, fight for them to be generously compensated, but also to take responsibility for a difficult decision.

This, however, as @Floppy pointed out on Slack, conflicts with A. what's written in the manifesto at Transport 4.1 and B. what he has said during the campaign for Horsham.

This is [Transport 4.1](http://openpolitics.org.uk/manifesto/transport.html#end-uk-airport-expansion):
> Until the aviation industry is carbon neutral, there will be no further expansions (such as new runways or terminals) of any UK airports, and capacity shall be capped at roughly current levels.

This is a quote from James at the [CPRE Sussex hustings in March](http://somethingnew.sayit.mysociety.org/speech/649136): 
> It's a no, I'm not in favour. But I'm also not in favour of airport expansion at Heathrow, I'm not in favour of a Boris Island [applause], or any of these things. Because fundamentally, and I'm going to again kind of reiterate what I said earlier, it comes down to the fact that climate change is a massive problem and we have to deal with it quickly. Aviation is a large contributor to that and anything we do that's heading us in the wrong direction, is just a bad idea.

I'm obviously not presenting any arguments for and against, I'm just pointing out what has been said and that now is the time to have a discussion about it so that we can take both sides of the argument into account and come to a reasoned conclusion.

**Comment by philipjohn** [comment]
Thanks for posting this, it's good to have this discussion.

We already have local manifesto pages for Horsham and SW Surrey so a London one is straightforward, and I'm happy to set that up tomorrow and copy in the current text.

That'll need chatting through with Lindsey of course though - hopefully @hiltona can help with that.

I've started a [branch](https://github.com/openpolitics/manifesto/tree/london-manifesto) to incorporate the London manifesto here, and I'll start copying that over tomorrow.

**Comment by andrewdwilliams** [comment]
Obviously this issue is contentious because Lindsey's running on it for London Mayor. But the London Mayor election is 5 May next year. The [Airports Commission](https://en.wikipedia.org/wiki/Airports_Commission), which was set up to decide which airport expansion was best economically and environmentally will be making their report within a few weeks. Perhaps it would be for the best to wait and see what their findings are before making any firm decisions.

On the other hand, what is in the Manifesto already has considerable worth. What we're facing is much more than a crisis surrounding Britain's airports getting full, what we're facing is a climate crisis. And, as it has been pointed out, aviation is one of, if not the biggest contributor to global warming in our country. To expand any airport, no matter how environmentally friendly, would still have huge environmental impacts that would be hard to eradicate. What we should be working for is a carbon neutral aviation sector, rather than just a bigger one.

Those are my brief thoughts.

**Comment by andrewdwilliams** [comment]
Obviously, since we opened this, the Airports Commission have made their [final report](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/440316/airports-commission-final-report.pdf), recommending an expansion of Heathrow. What we have to look at now is the reasoning in the report (I have yet to do so), and look at what options are on the table, in the knowledge that the 3 year, £20 million report recommends, unanimously, Heathrow.

**Comment by Floppy** [comment]
Yeah - I think the London campaign is very up in the air at the moment. It will depend who wants to get involved and stand, but I think until the manifesto is changed, then it's the main source of policy. Although, Something New doesn't preclude candidates from disagreeing on aspects of it (though this is a pretty big one).

**Comment by Floppy** [comment]
A change is proposed in #417 that's relevant to this. Closing this one off as stale though, we can take discussion over there. Can reopen if necessary.
