### ISSUE TITLE
Kicking the website

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/manifesto#380]
I noticed today that [faa3752df153f4a0ef3481203c523c017ef2f9c2] doesn't seem to have made it's way onto [the site](http://openpolitics.org.uk/manifesto/democracy.html). Same on the [SN site](https://somethingnew.org.uk/manifesto/democracy).

Not sure how that works, else I'd kick it myself. Feel free to educate me so I can in future :)

**Comment by Floppy** [comment]
Ah that's my fault, I haven't updated the submodules on those sites. Thanks for the kick. I'll trade you an upvote on #375 :)

**Comment by Floppy** [comment]
Fixed.
