### ISSUE TITLE
"Votebot" vs Pull Requests is different?

### ISSUE THREAD

**Issue by davidmiller** [openpolitics/manifesto#382]
Hi all,

Reading [Contributing](http://openpolitics.org.uk/contributing.html) I expect the [Votebot page](http://votebot.openpolitics.org.uk/) to be basically a different UI onto [openpolitics/manifesto/pulls](https://github.com/openpolitics/manifesto/pulls) but there seem to be no things in the Votebot page for me - is that expected? Am I reading the contributing page wrong or misunderstanding what Votebot is supposed to be?

**Comment by Floppy** [comment]
Mm, yes, I think (discovered yesterday actually) that currently it's not showing open votes. I'll have a crack at fixing it this evening. The UI is rather shonky anyway and needs an upgrade.

**Comment by Floppy** [comment]
Take a look now, it's actually working. Definitely needs improvement though.
