### ISSUE TITLE
What is the openpolitics workflow for "questions" ?

### ISSUE THREAD

**Issue by davidmiller** [openpolitics/manifesto#383]
Hi all, 

As a new contributor 
I want to discuss the manifesto
So that I can understand the context in which it was made. It's a complex document, and there is clearly a culture around it. I currently have questions, but they haven't yet become "Changes". (Which is perhaps the next step.)

Is this issues list the right place to ask policy questions about the manifesto and have discussions prior to suggesting specific changes? Would you suggest something else?

**Comment by Floppy** [comment]
This is a very good question. Currently we're doing that in issues, but it's completely opaque to the new user. I've also created a policy playground area in the Something New discourse forum, but I'm not sure what the right approach is.

Ideally I'd like a discussion to be opened up, and then be able to become a pull request when someone writes something, and the whole thing to have a similar UI for new users as the existing editing process.

**Comment by Floppy** [comment]
I don't think github allows empty pull requests yet, but we could have something that adds an empty commit to open a discussion; that's doable.

**Comment by davidmiller** [comment]
Perhaps a simple version would be a subtle (perhaps on hover) [Discuss this section](https://github.com/openpolitics/manifesto/issues/new?title=4.1%20[Add%20your%20title%20here]&body=[Add%20your%20question%20or%20comments%20here]&labels=policy) link / CTA?

**Comment by Floppy** [comment]
mm, that might be nice.

**Comment by Floppy** [comment]
I'm adding an ideas section in https://github.com/openpolitics/votebot/pull/84, which might resolve this to an extent. Reopen on the votebot repository if not, as it's more of a meta feature for the tool, I think.
