### ISSUE TITLE
Sub-section Introductions

### ISSUE THREAD

**Issue by OliverJackson1** [openpolitics/manifesto#391]
As a new user, there is a lot to read in the manifesto to get an overview of the positioning of openpolitics on specific issues. Nothing wrong with that if you have the attention span to stick with it. Some people might not though. So, how do people feel about introducing short snappy intro's to each sub-section that could roll up to form a concise full manifesto?

Nothing longer than a short of the section and key points.

Example: Communication

"We believe that individual privacy and government transparency are the cornerstone of Freedom and Liberty. This is why we oppose communication surveillance and government censorship and support internet freedom and net neutrality."

etc. for other sub-sections.

**Comment by Floppy** [comment]
I think we did have these in some places, but not everywhere; I'll check. It's quite obviously a good idea :)

**Comment by Floppy** [comment]
Of course, anyone could write those sections as well :)

**Comment by andrewdwilliams** [comment]
Yes, I think these are a good idea for setting out our general philosophy on different policy areas. I did a mini introduction for the overseas territories section the other day.

**Comment by OliverJackson1** [comment]
I've put the wording above in as an amendment. Feel free to request amendments or changes.

**Comment by Floppy** [comment]
We try to do these now. There are a couple more to write, which I'll pop on the list.
