### ISSUE TITLE
Archive using Wayback Machine

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/manifesto#393]
The Wayback Machine holds snapshots of websites but relies on its crawler. Inspired by [this WordPress plugin](https://wptavern.com/new-archiver-wordpress-plugin-auto-generates-wayback-machine-snapshots) I suggest we build into the manifesto a ping to automatically update the Wayback Machine when it changes.

**Comment by andrewdwilliams** [comment]
I agree this is a good idea, although I wouldn't be any help in implementing it.

**Comment by Floppy** [comment]
As discussed on SomethingnewUK/somethingnew.github.io#9, I bet we could do this with a github hook.

**Comment by philipjohn** [comment]
Looks like that hook has been working - I see indexes on archive.org that correspond with commits to the SN web site, so I've added the same webhook over to here.

**Comment by Floppy** [comment]
Oh, nice one. Is it archiving the deep pages, do you know, or just the homepage?

**Comment by philipjohn** [comment]
It does seem to be getting deeper pages but one of the commits I checked
was a change to an event page and the archive.org cache for that day was
out of date, so I'm not entirely sure.

On 15 Dec 2016 10:30 a.m., "James Smith" <notifications@github.com> wrote:

Oh, nice one. Is it archiving the deep pages, do you know, or just the
homepage?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<http://mailtrack.somethingnew.org.uk/wf/click?upn=HCCGVSkuisReePm2twCBLNS-2BlrB4ijVhyOYYYIaq1wsS5L-2BlF8pyVi283CT2LAcu-2B0U3edr-2FTsmD-2FcIz6IOxfCzdLJQq7qr7Q7MonheG29c381FCnQAZ0NVZJ3eE5SHj_s5UH8bhnBaopYjthcNSRcYOI2TopavFN7du3ESXcuEQX3lXc9uUpSnRVnFu0V-2BarpgW0xDIw8WWRfK-2FRIvCPzDRidVcLCxt8IBGUEy04ycFx9W2LD7xFSkrjVNo4kJ3TqQe-2FJOLbzufY-2BmM0rBvPnuICTdCqahqxEfybFc1Pwk7uDCOnpcNGdPKIwwiDA-2F1sNW8uLD-2BtpnR8geQRLzg4btaN5j0Dg3H-2BAKHk-2BjeGkDeRUJepYVz-2FVCWV5Ef0ocb4OhrcjSHYhhucqZH-2FuyHMGeoB82U6HL2VKLxkZAa-2BifPDNEN4X2KPsbdYKsgZCXcedl2qKFN3yig8iri8WSHFVQ-3D-3D>,
or mute the thread
<http://mailtrack.somethingnew.org.uk/wf/click?upn=HCCGVSkuisReePm2twCBLFmK4wepLeKS7UdiqXW-2BRKhXAnr7fNpdCB06bApzfcHyRv53XZMXqzk-2FV69Pxw4qhLOL0rUW-2Bje3q2-2BQ8dDFjsBBCnu0-2Fwv-2FTt6NScHXkBBl-2F5gu834xdgK6-2BtsagZL7Vg-3D-3D_s5UH8bhnBaopYjthcNSRcYOI2TopavFN7du3ESXcuEQX3lXc9uUpSnRVnFu0V-2BarpgW0xDIw8WWRfK-2FRIvCPzDRidVcLCxt8IBGUEy04ycFx9W2LD7xFSkrjVNo4kJ3TqQe-2FJOLbzufY-2BmM0rBvPnuICTdCqahqxEfybFc1Pwk7uDCOnpcNGdPKIwwiDA-2F1sBl31z-2BIaXdzREh-2BouwiIH-2FtbwRoO6duAz-2FO2LJt6lSeCocRsI9PlFfTiFC44vJbYZ2M7kgh6n1wV-2FQ-2B-2FqAHnHbYeAugnQL6jrfdb7IlNQ5Om2-2FPJXniQewiz-2FelsOKoXqlxp0yQ-2Fu5KJNK9K3X4UwA-3D-3D>
.
If you would like to unsubscribe and stop receiving these emails click here: http://mailtrack.somethingnew.org.uk/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcYOI2TopavFN7du3ESXcuEQX3lXc9uUpSnRVnFu0V-2BarpgW0xDIw8WWRfK-2FRIvCPzDRidVcLCxt8IBGUEy04ycFx9W2LD7xFSkrjVNo4kJ3TqQe-2FJOLbzufY-2BmM0rBvPnuICTdCqahqxEfybFc1Pwk7uDCOnpcNGdPKIwwiDA-2F1skPM-2Bl9YFph-2FOzVwQcuZYleflDsfiHOQMw-2FMq2ox8kyaBMduN09urYFe7JHNMlwF32cutCAo5oZzy-2BBdqqpIlY9VYYTBdl4AfE4dB9Kqj97DnFGoC1O9evdENn6Gqig0xAcEw9UnAOEzm5BwrSFSfYQ-3D-3D.
