### ISSUE TITLE
Altering the Manifesto Concerning Armed Forces

### ISSUE THREAD

**Issue by Xyleneb** [openpolitics/manifesto#434]
Hello, today I've been thinking about military intervention and stuff, and while I was at it I had a look at what you've got so far on the military manifesto.

Discounting the flagship policy which I know you won't change without a substantial 'counter-mandate' I've spotted a couple of other problems which I think you might agree with me on:

2.2 Issue 1: Change the phrase 'should be' to 'will be'.

2.2 Issue 2: Remove the line [...armed forces will be structured to...] "providing support to UK emergency services, during natural and civil disasters." This is an issue of clarification more than anything. Are you saying you will reduce the distinction between military personnel and police? No?

Well, the intent is clear from the sentences prior, so much that removal of this line actually helps to clarify it.

4.1 Issue 1: Again with the 'shoulds be' 'coulds be' and 'wouldn't it be nice if's'. In the context of Green Party eco-friendly tunnel bypasses I would understand it. They're extraordinarily expensive and it's a promise that probably won't be kept. But here, if you can fathom keeping the promise; make it. The public will see through any phony non-commitments eventually such that you may as well not make them.

5.1 Issue 1: "PMSCs will have to seek approval with the regulatory body before accepting operational deployments."

This is the most controversial proposal I think I've got. Keeping this line essentially forces PMSCs abroad or under ground outside of your "gold standard" jurisdiction, which is both counter-intuitive and loses money. Remove this line and enforce the standards detailed in 5.2, and you've got a system which rewards (or punishes) the appropriate conduct in war.

So, I propose that you remove this line/condition.

I will make some additions (rather than proposed retractions) as soon as I get the time to take some care in writing them. That's all, thanks very much.

**Comment by Floppy** [comment]
Hi @Xyleneb, this is all good stuff, are you still intending to pop it into a collection of edits? Keep them small, and we can get as many in as possible nice and easily. Do the removals and big changes too though, we can and should discuss them properly!

**Comment by Floppy** [comment]
Closed as #446 accepted.
