### ISSUE TITLE
Over-arching economic/investment policy

### ISSUE THREAD

**Issue by andrewdwilliams** [openpolitics/manifesto#442]
So, I've been doing some looking around on an over-arching economic policy that defines the rest of our economic policies. I was wondering if anyone had any thoughts. Especially how this works with existing Infrastructure and Economic policies.

I'm yet to have a look at taxation, but I have concerns about the idea of a Financial Transaction Tax, especially with 'Brexit' looming and the (at least initial) reliance required on the financial sector.

- Re-nationalise the UK Green Investment Bank and rename and restructure it as the National Investment Bank (NIB). The NIB will also be merged with the Public Works Loan Board and the Infrastructure and Projects Authority.
- The NIB shall be capitalised with £20 billion, drawn primarily from the sale of the government’s shares of private banks following the financial crisis, the removal of [subsidies for fossil fuels](https://openpolitics.org.uk/manifesto/environment.html#subsidies), and the existing funds held by the UK Green Investment Bank.
- The aim will be to raise £500 billion in investment over the next 20 years and invest that into infrastructure and technology.
- The NIB will target particularly deprived or underfunded regions, and local authorities will also be able to make the case for investment in their region.
- Initiate a Green New Deal to develop a 21st-century infrastructure:
   - Focus on low-carbon infrastructure and technology, including public buildings, public spaces, public services and other long-term assets and facilities.
   - Launch a Public Works Agency that is funded by the government and directly employs people to work on these public works programmes.
    - The NIB shall be able to raise its own capital through borrowing and issuing bonds, and issue low-interest loans to private sector projects it deems worthy of investment. It shall, in effect, operate as a bank, rather than a fund.

An important source: https://www.publications.parliament.uk/pa/cm201011/cmselect/cmenvaud/505/505.pdf

**Comment by Floppy** [comment]
This looks great, are you going to roll it into an edit on the economy page?

**Comment by andrewdwilliams** [comment]
Yeah, I'll do that.
