### ISSUE TITLE
Duplicates in menu

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/manifesto#469]
I only just noticed that the contents menu on manifesto pages is duplicating sections. I noticed on the [economy](https://openpolitics.org.uk/manifesto/economy.html) but it's happening on others too.

![contents](https://cloud.githubusercontent.com/assets/136342/23720815/beb913fa-0437-11e7-8136-ad13ba91f56d.png)

**Comment by Floppy** [comment]
That's very wierd, I don't see that?

Ah, I know why - it used to be done in markdown, but now it's built on the fly with Javascript; what browser are you in?

**Comment by philipjohn** [comment]
Ohhh interesting. Chrome 56 on Ubuntu 16.04. I don't see any console errors.

I don't see the same issue in Firefox 51.

**Comment by Autumn-Leah** [comment]
This has been happening for me too, Chromium 55 and Opera 42 on Ubuntu 16.10, Firefox 51 doesn't seem to have the issue for me either.

**Comment by Floppy** [comment]
Ah, I normally use Firefox, so it probably works there but nowhere else. Typical. Thanks!

**Comment by Floppy** [comment]
This issue was moved to openpolitics/openpolitics.github.io#5
