### ISSUE TITLE
Tried to respond to a post on a page that I hadn't reloaded, bot posted it instead

### ISSUE THREAD

**Issue by Autumn-Leah** [openpolitics/manifesto#478]
https://github.com/openpolitics/manifesto/pull/474#issuecomment-286181213

the bot posted something that I was going to post and then edit into a response

**Comment by Floppy** [comment]
This is very odd... I just added a config variable that might have restarted the app, hence this started happening just now, but I have no idea why it would. I'll investigate urgently.

**Comment by Floppy** [comment]
This issue was moved to openpolitics/votebot#88
