### ISSUE TITLE
2 members who should turn up as contributors don't

### ISSUE THREAD

**Issue by Autumn-Leah** [openpolitics/manifesto#480]
https://votebot.openpolitics.org.uk/users isn't showing https://votebot.openpolitics.org.uk/users/ghaggart or https://votebot.openpolitics.org.uk/users/chrisjsimpson as contributors. Github is showing them as having made a merge, putting them on the github list but not the site list. Whether they have voting privs or not is something I don't know. Already told @Floppy, figured I should make it an official issue; do it properly, if you will.

**Comment by Floppy** [comment]
Thanks, I'll investigate.

**Comment by Floppy** [comment]
This issue was moved to openpolitics/votebot#89
