### ISSUE TITLE
Propsed continuation of E.E.C. membership via EFTA as opposed to E,U. commitment

### ISSUE THREAD

**Issue by billiedreamwalker** [openpolitics/manifesto#516]
As someone belonging to the generation who voted to join the E.E.C., I would like to set some facts straight here.
First,  I am not a supporter of the E.E.C. or the E.U. I am, however, a supporter of Democracy and , just as I reluctantly accepted E.E.C. membership ,if the people had voted to remain in the EU then  I would have accepted that.

Let's be frank, however, Britain was NEVER asked to become a member of the EU.
France , and a few other Nations were and their own Governments overruled the people's wishes.
If we had joined the EU, why would there even have been referendums ?
Today's generation seems to believe we were given a choice decades ago. we were most emphatically NOT given a choice!
In the 1970's all that existed was the E.E.C. I was there, how many of you were?

The E.U. is a Political Party dream , it is not the peoples. Perhaps some consider that unimportant, so let's view this in perspective..
The people of Scotland voted to stay part of Great Britain because Independance was the S.N.P's dream not the people's.All the people wanted was Devo-max,, but the " Party" ensured that was not an option. If it had been Sturgeon would have no case for a second referendum.
The same is I believe the dream of ALL peoples regardless of Nation. The current policy of remaining in the EU, is ill-informed and not " evidence-based " , ( a priority itself open to gross misinterpretation and manipulation ).The information you leave out is just as important as the information you leave in.
So, the facts are that my generation voted to join the E.E.C. only.
So too did France and the other Nations mentioned who were offered referendums.Countries outside of the EU still remain members of the E.E.C. so why are the British being told they can't remain in the E.E.C. after Brexit?
Despite the claims made by Eurocrats the EU is _not_ the E.E.C.
Switzerland, Norway,Iceland and Lichtenstein are Members of the E.E.C. via EFTA and the legal precedent to be independant of the E.U. was set when the E.E.C. was formed _without the E.U_.
I would therefore ,suggest ,that if SomethingNew genuinely cares for democracy, the Manifesto be changed to allow the people themselves to determine the level of European Involvement and that an OR clause is introduced to the section on Europe to verify what they are being asked to support and vote for.
i.e. Should we support the EU and all of it's Institutions or The E.E.C. trading partnership via EFTA. If this is included as a public voting option, all well and good. On the other hand, if it isn't ,I would find it hard to remain a member of a group that has blinkered vision.
To be clear about this. I want a future for the younger generation that has NO political party's and that can't happen without the elimination of Political Policies that are not collectively shaped by the people.If I am wasting my time here, and my words are considered unimportant , let me know, and I will go elsewhere.
I think, that would be a shame, however, as I believe I have a lot to contribute to an organisation which is genuinely commited to political change.
An Open Politcs party should have open minds.
Your manifesto says that nothing should be hidden yet ignoring the very significant distinction between the E.U. and the E.E.C. is hiding the facts.Likewise,promoting  Devo-Max for all nations in Europe is an " Open " policy, but presenting the issue as the EU or nothing option is an example of a political party embracing the closed shop.

**Comment by Floppy** [comment]
This is true, we don't have policy explicitly in there on the different aspects of Europe, and on which we should follow post-brexit (or even what our preferred EU option is). We should get this stuff in as a matter of priority. If you would like to write something, please do! On this topic it will definitely be easier to accept a number of small changes on different aspects, I think.

**Comment by Floppy** [comment]
I also wanted to include the DiEM25 proposals into the manifesto - they should go in as an option for if the UK does remain (which I admit at this point is pretty unlikely).

**Comment by billiedreamwalker** [comment]
I disagree regarding DiEM25.
Having visited the site in question I find the attitude to Brexit voters
not only dismissive but insulting.the argument of " I am right so you are
wrong ," is emotional, irrational and insipid.
That does appear to be the attitude.
In any case ,where does all of this constant reinvention and jockeying for
position stop.I feel the ordinary member is being left way behind and
his/her input becoming increasingly insignificant.
I feel this way after only a few days?
There is something seriously wrong here

**Comment by Floppy** [comment]
I've suggested a policy improvement to remain in the EEA and EFTA in #518.

**Comment by Floppy** [comment]
it's in :)
