### ISSUE TITLE
Government Procurement

### ISSUE THREAD

**Issue by areteh** [openpolitics/manifesto#553]
I'm not sure which section this would best fit under. The idea(s) are to:

1) Drive savings by transitioning to open source SW
2) Use savings to provide every child with a Rasberry Pi
3) Stimulate innovation on the demand side by requiring that 5% of Government Procurement comes from copanies meeting 2 of the following 3 criteria:
	* Fewer than 20 employees
	* Established within the last 3 years
	* A spin-out of UK University technology

**Comment by Floppy** [comment]
Thanks @areteh! I'll close this idea off as it's under discussion in #555 now.
