### ISSUE TITLE
On the spot fines for littering enforced countrywide

### ISSUE THREAD

**Issue by simonneb** [openpolitics/manifesto#599]
A minimum £20 on the spot fine will be enforced nationally by local authorities and police for littering. £20 will be for each piece of litter rather than a single fine for a single littering incident.

**Comment by Floppy** [comment]
Thanks @simonneb! This has come into the ideas list rather than as a proposal (probably because I've done some confusing user interface flow somewhere). I see you've done your flooding proposal though; perhaps you'd like to resubmit this as one of those?

**Comment by simonneb** [comment]
Sure no problem!

**Comment by Floppy** [comment]
Great, thanks. I'll close this once you've done it. On another note, any feedback on user interface or workflow that you might have would be super-useful as an issue on https://github.com/openpolitics/votebot/issues - I worry we're pointing people in the wrong directions :)

**Comment by simonneb** [comment]
Added to my branch - ill close the comment
