### ISSUE TITLE
Get hyped

### ISSUE THREAD

**Issue by Xyleneb** [openpolitics/manifesto#625]
Hello, I've been taking some time out from political stuff throughout last year and for good reason I think. There's still a lot of stuff that I've hardly even begun to do, but even so I think I'll have a policy or two to offer up for this year (I'll have a notebook with some ideas scribbled in it and one or two of them ought to be worthwhile). The first thing I'll look at is "Vehicle Excise Duty and Fuel Duty No.3". I'll be surprised if it winds up differing from revision 2 (#477 ) much... but as long as a great vacant hole remains in the budget from the 'scrap road tax policy' nothing else seems much important. Yes, another year another revision... But revision 3 will be the one to fix it. It will be worth all the hype!!!!!!!! :^I

**Comment by Floppy** [comment]
Yaay! This work always goes in bursts for me too, too much politics and it gets overwhelming. Nice to see you again :)
