### ISSUE TITLE
Re-Establish Sovereign Money Creation.

### ISSUE THREAD

**Issue by tonefreqhz** [openpolitics/manifesto#641]
”There is no Science, the Study of which is more useful and commendable than the Knowledge of the true Interest of one’s Country; and perhaps there is no Kind of Learning more abstruse and intricate, more difficult to acquire in any Degree of Perfection than This, and therefore none more generally neglected. Hence it is, that we every Day find Men in Conversation contending warmly on some Point in Politicks, which, altho’ it may nearly concern them both, neither of them understand any more than they do each other.
Thus much by way of Apology for this present Enquiry into the Nature and Necessity of a Paper Currency. And if any Thing I shall say, may be a Means of fixing a Subject that is now the chief Concern of my Countrymen, in a clearer Light, I shall have the Satisfaction of thinking my Time and Pains well employed.
To proceed, then,
There is a certain proportionate Quantity of Money requisite to carry on the Trade of a Country freely and currently; More than which would be of no Advantage in Trade, and Less, if much less, exceedingly detrimental to it.
This leads us to the following general Considerations.”
http://founders.archives.gov/documents/Franklin/01-01-02-0041
https://longhairedmusings.wordpress.com/?s=franklin+money

Dr Adrian Wriggley, Tax , Banking , PaperEdit
https://publications.parliament.uk/pa/cm201011/cmselect/cmtreasy/753/753vw30.htm

PRINCIPLES OF TAX POLICY ARE ECONOMIC AND POLITICAL

11.  National success can only be sustained with a sound system of taxation. Sound taxation must be based on policy principles thoroughly understood by those empowered to maintain it. These must be based on an understanding of the economic principles underlying taxation. Equally important is an understanding of the political principles behind taxation.

UNDERSTANDING TAXATION

12.  Taxation is central to the interests of every citizen, business and special group. Each group has its own economic interests and perspective foremost when it analyses the economy and promotes a particular viewpoint. Politicians, economists and business people rarely promote analysis which conflicts with their group interests. Clarity and analytical integrity generally work against private interests and are usually absent.

13.  In this response, it is assumed The Committee is seeking to further the public interest, even where this may conflict with the private interests which usually dominate the analysis and debate. This will pose a major challenge to those who have learned their analysis exclusively through channels devoted to promoting private interests, and must "unlearn" erroneous but pervasive assumptions and principles.

WHAT ARE THE ECONOMIC PRINCIPLES OF TAXATION?

14.  Taxation is at the economic core wherever government supplies significant services such as civil and military protection of property rights, infrastructure, education or healthcare. The UK is no exception.

15.  Taxation comprises three fundamental economic parts:

—  Creation of the medium of taxation and issue into the economy

—  Distribution of the medium of taxation through the economy

—  Collection of the medium of taxation

https://policy.greenparty.org.uk/ec.html
Check out policy EC661 
"The Green Party believes that, as the means of exchanging goods and services, the stock of money is a vital common resource which should be managed in the public interest. Yet only 3% of our money supply currently exists in the form of notes and coins issued by the Government or the Bank of England. 97% of the money circulating in the economy takes the form of credit that is created electronically by private banks through the accounting processes they follow when they make loans. for an idea of the full extent of tax payer value of such a policy"
 see. Positive money why taxes are so high
https://positivemoney.org/issues/taxes/

`<a data-quiz="QYMG3AR" data-type=4 href="https://take.quiz-maker.com/QYMG3AR">Loading...</a><script>(function(i,s,o,g,r,a,m){var ql=document.querySelectorAll('A[quiz],DIV[quiz],A[data-quiz],DIV[data-quiz]'); if(ql){if(ql.length){for(var k=0;k<ql.length;k++){ql[k].id='quiz-embed-'+k;ql[k].href="javascript:var i=document.getElementById('quiz-embed-"+k+"');try{qz.startQuiz(i)}catch(e){i.start=1;i.style.cursor='wait';i.style.opacity='0.5'};void(0);"}}};i['QP']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://take.quiz-maker.com/3012/CDN/quiz-embed-v1.js','qp');</script>`
https://take.quiz-maker.com/QYMG3AR

`<iframe width="640" height="360" scrolling="no" frameborder="0" style="border: none;" src="https://www.bitchute.com/embed/esC7sz7rqcSG/"></iframe>`
https://www.bitchute.com/video/esC7sz7rqcSG/

Understanding Affordable House Building and Finance.
https://issuu.com/homeatix/docs/home_ix_affordable_homes_a_framework_of_understan

**Comment by Floppy** [comment]
If you want to add this as a manifesto proposal, go ahead, but the issue tracker isn't the right place for it :)
