### ISSUE TITLE
Ask for evidence

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/manifesto#71]
Quick suggestion: we should collectively take a cue from Sense About Science in formulating the manifesto and [Ask For Evidence](http://www.senseaboutscience.org/pages/a4e.html).

**Comment by tmtmtmtm** [comment]
I definitely like the idea of another vote type. There are quite a few proposals for which I don't particularly want to vote No, as I'm not necessarily against the idea, but where I believe there needs to be much more explanation given. The changes in #270 mean I'll probably *need* to start voting No on them, but I'd prefer to have an alternative vote type instead.

**Comment by Floppy** [comment]
What do you think the result of an evidence vote should be? Is it effectively the same as the block, but without the negative connotations?

**Comment by Floppy** [comment]
I will attempt to choose an icon from http://www.emoji-cheat-sheet.com/. Fun.

**Comment by Floppy** [comment]
Probably :question: is most appropriate :)

**Comment by tmtmtmtm** [comment]
> Is it effectively the same as the block, but without the negative connotations?

Kind of. And maybe it's just a matter of adjusting my own understanding of the meanings, but I see a 'no' vote as "I think this is a bad idea", whereas this would be "I don't know yet whether this is a good idea or a bad idea, and there isn't enough here to decide".

**Comment by tmtmtmtm** [comment]
If we wanted there to be *some* distinction from a 'No', then perhaps it isn't a complete block — with sufficient (FSVO) Yes votes, the PR could still be approved anyway (though perhaps only manually, rather than automatically?)

I suspect we want to see how it plays out in a few cases first, though.

**Comment by philipjohn** [comment]
> Any contributor can block a merge by including a ‘thumbs-down’ symbol, as long as they include constructive reasoning and alternative proposals.
http://openpolitics.org.uk/contributing.html

I think it'd be worth being clearer on the rules in this respect though (in a separate PR!)

> If we wanted there to be some distinction from a 'No', then perhaps it isn't a complete block

The hand emoji would perhaps work well for that? A hand could perhaps cancel out a thumbs up?

**Comment by tmtmtmtm** [comment]
> A hand could perhaps cancel out a thumbs up?

There's something nice about that, though I'm worried about the case where a few people vote yes straightaway on gut instinct. Then (especially in a post #270 auto-committing world), simply saying "Hey, there's no evidence provided here at all" with a hand, or question mark, or whatever, wouldn't be enough.

Perhaps only Yes votes made *after* someone raises this should count? i.e. if enough people think it should be approved anyway, even with no evidence, they can simply revote Yes on it?

**Comment by Floppy** [comment]
OK, I will do something in #270 on this. @philipjohn, any vote will cancel a previous one, so yes, an abstention will remove a yes vote without it becoming a no.

**Comment by tmtmtmtm** [comment]
I read @philipjohn's suggestion as being that a 'hand' would cancel out a 'thumbs up' *from someone else*.

i.e. if you need two yes votes, then Yes, Yes, Hand would total one, not two; whereas Yes, Yes, Yes, Hand would be enough.

**Comment by Floppy** [comment]
Oh, I see. @philipjohn, is that what you meant?

**Comment by philipjohn** [comment]
I was thinking that;

:+1: = vote to merge
:hand: = not sure, cancels out one :+1: but doesn't block
:-1: = block

So;

Votes                        | Result
--------------------------- | -----------------------------
:+1: :+1: :hand:         | One more :+1: needed
:hand:                       | 2 :+1: needed
:hand: :+1:                | 2 :+1: needed
:hand: :+1: :+1:         | 1 :+1: needed
:+1: :+1:                    | Merge
:+1: :+1: :hand:         | 1 :+1: needed
:+1: :+1: :+1:  :hand: | Merge

**Comment by Floppy** [comment]
Ah, OK, that might work. :hand: doesn't do much at the moment, so we could change its meaning quite easily to "wait" rather than "abstain", which is quite frankly meaningless.

**Comment by Floppy** [comment]
Presumably in your table above, then the second row should read "3 :hand: needed" ?

**Comment by philipjohn** [comment]
Yes, sorry - now corrected
